name             'bitmonk_monitor'
maintainer       'Justin Alan Ryan'
maintainer_email 'bitmonk@icloud.com'
license          'Apache 2.0'
description      'Installs/Configures bitmonk_monitor'
long_description 'Installs/Configures bitmonk_monitor'
version          '0.1.0'
